#################
### AUTOSTART ###
#################

exec-once = ghostty &
exec-once = brave &
# exec-once = discord &
exec-once = hypridle &
exec-once = waybar &
exec-once = killall -q awww;sleep .5 && awww-daemon
