TS_SEARCH_PATHS=($HOME/ ~/images ~/.local/ ~/work ~/personal ~/.config)

TS_EXTRA_SEARCH_PATHS=()

TS_IGNORE_PATHS=($HOME/.vim $HOME/personal $HOME/go $HOME/.oh-my-zsh $HOME/.ssh
$HOME/.pki $HOME/.local $HOME/.librewolf $HOME/work $HOME/.gnupg $HOME/.rustup
$HOME/.cache $HOME/.cargo $HOME/.config/gtk-3.0 $HOME/.config/discord
$HOME/.config/spotify $HOME/.config/GIMP $HOME/.config/pulse $HOME/.config/cava
$HOME/.config/dconf $HOME/.config/go) 

TS_MAX_DEPTH=1
