# defaults
set -g detach-on-destroy off

set -g default-terminal "tmux-256color"

set -g renumber-windows on
set -g base-index 1
bind c new-window -c '#{pane_current_path}'

# binds
set -g prefix C-a

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key k confirm-before -p "Kill current session? (y/n)" "kill-session -t \"#S\""
bind-key K confirm-before -p "Kill server? (y/n)" "kill-server"

bind-key N run-shell "~/.local/bin/tmux-sessionizer ~/notes"

# bar
set -g status-right '[#S]'
set -g status-left '#{?client_prefix,[⸸],}'

set -g window-status-format '#I:#W'
set -g window-status-current-format '[#I:#W]'

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.config/tmux/plugins/tpm/tpm'
